/* eslint-disable */
// @ts-nocheck
/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes made here will be overwritten during the next build.
 * 
 * Generated on: 2025-03-17
 */
import {
  // defineBreakpoints,
  defineComponents,
  // defineDesignTokens,
} from '@contentful/experiences-sdk-react';
import DMOButton from './dmo-button/DMOButton.react';
import { DMOButtonDefinition } from './dmo-button/DMOButton.studio';
import DmoContainer from './dmo-container/DmoContainer.react';
import { DmoContainerDefinition } from './dmo-container/DmoContainer.studio';
import DMOPage from './dmo-page/DMOPage.react';
import { DMOPageDefinition } from './dmo-page/DMOPage.studio';
import DmoText from './dmo-text/DmoText.react';
import { DmoTextDefinition } from './dmo-text/DmoText.studio';
  
const registerComponents = () => {
    defineComponents([
        
{
    component: DMOButton,
    definition: DMOButtonDefinition,
},

{
    component: DmoContainer,
    definition: DmoContainerDefinition,
},

{
    component: DMOPage,
    definition: DMOPageDefinition,
},

{
    component: DmoText,
    definition: DmoTextDefinition,
}
    ]);
};
export default registerComponents;
        