/* eslint-disable */
// @ts-nocheck
/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes made here will be overwritten during the next build.
 * 
 * Generated on: 2025-03-17
 */
import { ComponentDefinition } from "@contentful/experiences-sdk-react";

export const DMOPageDefinition: ComponentDefinition = {
  "id": "dmo-page",
  "name": "DMO Page",
  "category": "Components",
  "buildInStyles": [
    "cfWidth"
  ],
  "children": true,
  "variables": [
    {
      "type": "Text",
      "group": "style",
      "displayName": "Title"
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Slug"
    }
  ]
};