/* eslint-disable */
// @ts-nocheck
/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes made here will be overwritten during the next build.
 * 
 * Generated on: 2025-03-17
 */
import React, { useEffect, useRef } from 'react';
import { createElement } from "@lit-labs/ssr-react";


interface DMOPageProps {
    title: string,
	slug: string,
}

const DMOPage: React.FC<DMOPageProps> = (props) => {
    /* return <dmo-page
        title={props.title}
		slug={props.slug}>
			{props.children}
        </dmo-page>;*/

    const attrs = {
        title:props.title,
            slug:props.slug
    };

    const filteredProps = Object.entries(attrs).reduce((acc, [key, value]) => {
        if (value !== undefined) {
            acc[key] = value;
        }
        return acc;
    }, {});

    return createElement(
        "dmo-page",
        {
            suppressHydrationWarning: true,
            ...filteredProps
        },
			props.children
    );
};

export default DMOPage;

declare global {
    namespace JSX {
        interface IntrinsicElements {
            'dmo-page': React.DetailedHTMLProps<
                React.HTMLAttributes<HTMLElement>,
                Partial<DMOPageProps>,
                HTMLElement
            >
        }
    }
}