


export class CTFStudioManifest {

    constructor() {
        this.imports = [`/* eslint-disable */
// @ts-nocheck
/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes made here will be overwritten during the next build.
 * 
 * Generated on: ${new Date().toISOString().split('T')[0]}
 */
import {
  // defineBreakpoints,
  defineComponents,
  // defineDesignTokens,
} from '@contentful/experiences-sdk-react';`];
        this.definitions = [];
    }

    processCompDefinition(className, tagName) {
        this.imports.push(`import ${className} from './${tagName}/${className}.react';`);
        this.imports.push(`import { ${className}Definition } from './${tagName}/${className}.studio';`);
        this.definitions.push(`
{
    component: ${className},
    definition: ${className}Definition,
}`)
    }

    render() {
        return `${this.imports.join('\n')}
  
const registerComponents = () => {
    defineComponents([
        ${this.definitions.join(',\n')}
    ]);
};
export default registerComponents;
        `
    }

}