/* eslint-disable */
// @ts-nocheck
/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes made here will be overwritten during the next build.
 * 
 * Generated on: 2025-03-17
 */
import { ComponentDefinition } from "@contentful/experiences-sdk-react";

export const DmoContainerDefinition: ComponentDefinition = {
  "id": "dmo-container",
  "name": "Demo Container",
  "category": "Components",
  "buildInStyles": [],
  "children": true,
  "variables": [
    {
      "type": "Text",
      "group": "style",
      "displayName": "Background Color",
      "validations": {
        "in": [
          {
            "value": "dmai_background_default",
            "displayName": "Default"
          },
          {
            "value": "dmai_background_subdued",
            "displayName": "Subdued"
          },
          {
            "value": "dmai_background_primary_default",
            "displayName": "Primary Default"
          },
          {
            "value": "dmai_background_primary_subdued",
            "displayName": "Primary Subdued"
          },
          {
            "value": "dmai_background_secondary_default",
            "displayName": "Secondary Default"
          },
          {
            "value": "dmai_background_tertiary_default",
            "displayName": "Tertiary Default"
          },
          {
            "value": "dmai_background_neutral_default",
            "displayName": "Neutral Default"
          },
          {
            "value": "dmai_background_minimal",
            "displayName": "Minimal"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Border Color",
      "validations": {
        "in": [
          {
            "value": "dmai_border_default",
            "displayName": "Default"
          },
          {
            "value": "dmai_border_subdued",
            "displayName": "Subdued"
          },
          {
            "value": "dmai_border_inverted",
            "displayName": "Inverted"
          },
          {
            "value": "dmai_border_primary_default",
            "displayName": "Primary Default"
          },
          {
            "value": "dmai_border_secondary_default",
            "displayName": "Secondary Default"
          },
          {
            "value": "dmai_border_tertiary_default",
            "displayName": "Tertiary Default"
          },
          {
            "value": "dmai_border_on_surface_default",
            "displayName": "On Surface Default"
          },
          {
            "value": "dmai_border_warning",
            "displayName": "Warning"
          },
          {
            "value": "dmai_border_danger",
            "displayName": "Danger"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Border Width",
      "validations": {
        "in": [
          {
            "value": "dmai_border_width_none",
            "displayName": "None"
          },
          {
            "value": "dmai_border_width_sm",
            "displayName": "Sm"
          },
          {
            "value": "dmai_border_width_md",
            "displayName": "Md"
          },
          {
            "value": "dmai_border_width_lg",
            "displayName": "Lg"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Border Style",
      "defaultValue": "none",
      "validations": {
        "in": [
          {
            "value": "none",
            "displayName": "None"
          },
          {
            "value": "solid",
            "displayName": "Solid"
          },
          {
            "value": "dashed",
            "displayName": "Dashed"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Corner Radius",
      "validations": {
        "in": [
          {
            "value": "dmai_border_radius_none",
            "displayName": "None"
          },
          {
            "value": "dmai_border_radius_sm",
            "displayName": "Sm"
          },
          {
            "value": "dmai_border_radius_md",
            "displayName": "Md"
          },
          {
            "value": "dmai_border_radius_lg",
            "displayName": "Lg"
          },
          {
            "value": "dmai_border_radius_full",
            "displayName": "Full"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Padding",
      "validations": {
        "in": [
          {
            "value": "dmai_padding_0x",
            "displayName": "0x"
          },
          {
            "value": "dmai_padding_0_5x",
            "displayName": "0 5x"
          },
          {
            "value": "dmai_padding_1x",
            "displayName": "1x"
          },
          {
            "value": "dmai_padding_2x",
            "displayName": "2x"
          },
          {
            "value": "dmai_padding_3x",
            "displayName": "3x"
          },
          {
            "value": "dmai_padding_4x",
            "displayName": "4x"
          },
          {
            "value": "dmai_padding_5x",
            "displayName": "5x"
          },
          {
            "value": "dmai_padding_6x",
            "displayName": "6x"
          },
          {
            "value": "dmai_padding_7x",
            "displayName": "7x"
          },
          {
            "value": "dmai_padding_8x",
            "displayName": "8x"
          },
          {
            "value": "dmai_padding_9x",
            "displayName": "9x"
          },
          {
            "value": "dmai_padding_10x",
            "displayName": "10x"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Gap",
      "validations": {
        "in": [
          {
            "value": "dmai_gap_0x",
            "displayName": "0x"
          },
          {
            "value": "dmai_gap_0_5x",
            "displayName": "0 5x"
          },
          {
            "value": "dmai_gap_1x",
            "displayName": "1x"
          },
          {
            "value": "dmai_gap_2x",
            "displayName": "2x"
          },
          {
            "value": "dmai_gap_3x",
            "displayName": "3x"
          },
          {
            "value": "dmai_gap_4x",
            "displayName": "4x"
          },
          {
            "value": "dmai_gap_5x",
            "displayName": "5x"
          },
          {
            "value": "dmai_gap_6x",
            "displayName": "6x"
          },
          {
            "value": "dmai_gap_7x",
            "displayName": "7x"
          },
          {
            "value": "dmai_gap_8x",
            "displayName": "8x"
          },
          {
            "value": "dmai_gap_9x",
            "displayName": "9x"
          },
          {
            "value": "dmai_gap_10x",
            "displayName": "10x"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Layout Direction",
      "defaultValue": "column",
      "validations": {
        "in": [
          {
            "value": "row",
            "displayName": "Horizontal"
          },
          {
            "value": "column",
            "displayName": "Vertical"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Align Items",
      "defaultValue": "start",
      "validations": {
        "in": [
          {
            "value": "start",
            "displayName": "Start"
          },
          {
            "value": "center",
            "displayName": "Center"
          },
          {
            "value": "end",
            "displayName": "End"
          },
          {
            "value": "stretch",
            "displayName": "Stretch"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Justify Content",
      "defaultValue": "start",
      "validations": {
        "in": [
          {
            "value": "start",
            "displayName": "Start"
          },
          {
            "value": "center",
            "displayName": "Center"
          },
          {
            "value": "end",
            "displayName": "End"
          },
          {
            "value": "space-between",
            "displayName": "Space Between"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Horizontal Resizing",
      "defaultValue": "hug",
      "validations": {
        "in": [
          {
            "value": "fixed",
            "displayName": "Fixed"
          },
          {
            "value": "fill",
            "displayName": "Fill"
          },
          {
            "value": "hug",
            "displayName": "Hug"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Width"
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Horizontal Flex",
      "validations": {
        "in": [
          {
            "value": "1",
            "displayName": "1"
          },
          {
            "value": "2",
            "displayName": "2"
          },
          {
            "value": "3",
            "displayName": "3"
          },
          {
            "value": "4",
            "displayName": "4"
          },
          {
            "value": "5",
            "displayName": "5"
          },
          {
            "value": "6",
            "displayName": "6"
          },
          {
            "value": "7",
            "displayName": "7"
          },
          {
            "value": "8",
            "displayName": "8"
          },
          {
            "value": "9",
            "displayName": "9"
          },
          {
            "value": "10",
            "displayName": "10"
          },
          {
            "value": "11",
            "displayName": "11"
          },
          {
            "value": "12",
            "displayName": "12"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Vertical Resizing",
      "defaultValue": "hug",
      "validations": {
        "in": [
          {
            "value": "fixed",
            "displayName": "Fixed"
          },
          {
            "value": "fill",
            "displayName": "Fill"
          },
          {
            "value": "hug",
            "displayName": "Hug"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Height"
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Vertical Flex",
      "validations": {
        "in": [
          {
            "value": "1",
            "displayName": "1"
          },
          {
            "value": "2",
            "displayName": "2"
          },
          {
            "value": "3",
            "displayName": "3"
          },
          {
            "value": "4",
            "displayName": "4"
          },
          {
            "value": "5",
            "displayName": "5"
          },
          {
            "value": "6",
            "displayName": "6"
          },
          {
            "value": "7",
            "displayName": "7"
          },
          {
            "value": "8",
            "displayName": "8"
          },
          {
            "value": "9",
            "displayName": "9"
          },
          {
            "value": "10",
            "displayName": "10"
          },
          {
            "value": "11",
            "displayName": "11"
          },
          {
            "value": "12",
            "displayName": "12"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Internal Label"
    }
  ]
};