/* eslint-disable */
// @ts-nocheck
/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes made here will be overwritten during the next build.
 * 
 * Generated on: 2025-03-17
 */
import { ComponentDefinition } from "@contentful/experiences-sdk-react";

export const DmoTextDefinition: ComponentDefinition = {
  "id": "dmo-text",
  "name": "Demo Text",
  "category": "Components",
  "buildInStyles": [],
  "variables": [
    {
      "type": "Text",
      "group": "style",
      "displayName": "Text Color",
      "validations": {
        "in": [
          {
            "value": "dmai_text_default",
            "displayName": "Default"
          },
          {
            "value": "dmai_text_subdued",
            "displayName": "Subdued"
          },
          {
            "value": "dmai_text_minimal",
            "displayName": "Minimal"
          },
          {
            "value": "dmai_text_inverted",
            "displayName": "Inverted"
          },
          {
            "value": "dmai_text_warning",
            "displayName": "Warning"
          },
          {
            "value": "dmai_text_danger",
            "displayName": "Danger"
          },
          {
            "value": "dmai_text_primary_default",
            "displayName": "Primary Default"
          },
          {
            "value": "dmai_text_primary_inverted",
            "displayName": "Primary Inverted"
          },
          {
            "value": "dmai_text_secondary_default",
            "displayName": "Secondary Default"
          },
          {
            "value": "dmai_text_tertiary_default",
            "displayName": "Tertiary Default"
          },
          {
            "value": "dmai_text_tertiary_inverted",
            "displayName": "Tertiary Inverted"
          },
          {
            "value": "dmai_text_on_surface_default",
            "displayName": "On Surface Default"
          },
          {
            "value": "dmai_text_secondary_inverted",
            "displayName": "Secondary Inverted"
          },
          {
            "value": "dmai_text_on_surface_subdued",
            "displayName": "On Surface Subdued"
          },
          {
            "value": "dmai_text_on_surface_minimal",
            "displayName": "On Surface Minimal"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Horizontal Resizing",
      "defaultValue": "hug",
      "validations": {
        "in": [
          {
            "value": "fixed",
            "displayName": "Fixed"
          },
          {
            "value": "fill",
            "displayName": "Fill"
          },
          {
            "value": "hug",
            "displayName": "Hug"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Width"
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Horizontal Flex",
      "validations": {
        "in": [
          {
            "value": "1",
            "displayName": "1"
          },
          {
            "value": "2",
            "displayName": "2"
          },
          {
            "value": "3",
            "displayName": "3"
          },
          {
            "value": "4",
            "displayName": "4"
          },
          {
            "value": "5",
            "displayName": "5"
          },
          {
            "value": "6",
            "displayName": "6"
          },
          {
            "value": "7",
            "displayName": "7"
          },
          {
            "value": "8",
            "displayName": "8"
          },
          {
            "value": "9",
            "displayName": "9"
          },
          {
            "value": "10",
            "displayName": "10"
          },
          {
            "value": "11",
            "displayName": "11"
          },
          {
            "value": "12",
            "displayName": "12"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Vertical Resizing",
      "defaultValue": "hug",
      "validations": {
        "in": [
          {
            "value": "fixed",
            "displayName": "Fixed"
          },
          {
            "value": "fill",
            "displayName": "Fill"
          },
          {
            "value": "hug",
            "displayName": "Hug"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Height"
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Vertical Flex",
      "validations": {
        "in": [
          {
            "value": "1",
            "displayName": "1"
          },
          {
            "value": "2",
            "displayName": "2"
          },
          {
            "value": "3",
            "displayName": "3"
          },
          {
            "value": "4",
            "displayName": "4"
          },
          {
            "value": "5",
            "displayName": "5"
          },
          {
            "value": "6",
            "displayName": "6"
          },
          {
            "value": "7",
            "displayName": "7"
          },
          {
            "value": "8",
            "displayName": "8"
          },
          {
            "value": "9",
            "displayName": "9"
          },
          {
            "value": "10",
            "displayName": "10"
          },
          {
            "value": "11",
            "displayName": "11"
          },
          {
            "value": "12",
            "displayName": "12"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Internal Label"
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Typography",
      "defaultValue": "body-md",
      "validations": {
        "in": [
          {
            "value": "display-md",
            "displayName": "DisplayMD"
          },
          {
            "value": "heading-xl",
            "displayName": "HeadingXL"
          },
          {
            "value": "heading-lg",
            "displayName": "HeadingLG"
          },
          {
            "value": "heading-md",
            "displayName": "HeadingMD"
          },
          {
            "value": "heading-sm",
            "displayName": "HeadingSM"
          },
          {
            "value": "heading-xs",
            "displayName": "HeadingXS"
          },
          {
            "value": "body-lg",
            "displayName": "BodyLG"
          },
          {
            "value": "body-md",
            "displayName": "BodyMD"
          },
          {
            "value": "body-sm",
            "displayName": "BodySM"
          },
          {
            "value": "label-lg",
            "displayName": "LabelLG"
          },
          {
            "value": "label-md",
            "displayName": "LabelMD"
          },
          {
            "value": "label-sm",
            "displayName": "LabelSM"
          },
          {
            "value": "label-xs",
            "displayName": "LabelXS"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Text"
    }
  ]
};