/* eslint-disable */
// @ts-nocheck
/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes made here will be overwritten during the next build.
 * 
 * Generated on: 2025-03-17
 */
import { ComponentDefinition } from "@contentful/experiences-sdk-react";

export const DMOButtonDefinition: ComponentDefinition = {
  "id": "dmo-button",
  "name": "DMO Button",
  "category": "Components",
  "buildInStyles": [],
  "variables": [
    {
      "type": "Text",
      "group": "style",
      "displayName": "Emphasis",
      "defaultValue": "bold",
      "validations": {
        "in": [
          {
            "value": "bold",
            "displayName": "Bold"
          },
          {
            "value": "subtle",
            "displayName": "Subtle"
          },
          {
            "value": "minimal",
            "displayName": "Minimal"
          }
        ]
      }
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Design",
      "defaultValue": "primary",
      "validations": {
        "in": [
          {
            "value": "primary",
            "displayName": "Primary"
          },
          {
            "value": "secondary",
            "displayName": "Secondary"
          }
        ]
      }
    },
    {
      "type": "Boolean",
      "group": "style",
      "displayName": "Disabled"
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Label"
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "Target"
    },
    {
      "type": "Text",
      "group": "style",
      "displayName": "URL"
    }
  ]
};